services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php